# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dfef144a0d21036219340a7bedc9f72d55dc174f3be97cbe75cd4febfce0d72a67ddfb8abbe84aafac9a89a922d5f643ef2856d1bac3bceff8c67c8bc952916

test:
  secret_key_base: ebb3c6f5d548987d1ba7fc86eceb3341c2c47567349f1a6d3242b0d9d6c50f9014d708d218bb7d6ad6d3ce02ff70d875bbdf2fcba592e3539a4f88a5545c7c06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
